
  0%|                                                                                                                                                                                    | 0/313 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    trainer.train()
  File "/raid/home/rizwank/courses/DLCV/Project/train.py", line 94, in train
    loss, loss_dict = self.train_step(batch)
  File "/raid/home/rizwank/courses/DLCV/Project/train.py", line 39, in train_step
    loss_dict = self.criteria(output, batch)
TypeError: 'LambdaLR' object is not callable